# Generated by Django 2.2.24 on 2021-11-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211120_1107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
