# Generated by Django 2.2.24 on 2021-11-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(default=123123, max_length=500, verbose_name='Bio'),
            preserve_default=False,
        ),
    ]
