# Generated by Django 2.2.24 on 2021-11-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_doctor_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
