# Generated by Django 3.2.9 on 2021-12-08 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_result_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateField(default=datetime.date(2021, 12, 8)),
        ),
        migrations.AlterField(
            model_name='result',
            name='massage',
            field=models.TextField(default='Мануальна терапія'),
        ),
        migrations.AlterField(
            model_name='result',
            name='time',
            field=models.TextField(default='15:00'),
        ),
    ]
