# Generated by Django 3.2.9 on 2021-12-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211208_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='massage',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='time',
            field=models.TextField(),
        ),
    ]
