# Generated by Django 2.2.24 on 2021-12-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='surname',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Name'),
        ),
    ]
