# Generated by Django 3.2.9 on 2021-12-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211205_0052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'Result', 'verbose_name_plural': 'Results'},
        ),
        migrations.AddField(
            model_name='result',
            name='massage',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='result',
            name='time',
            field=models.TextField(default=None),
        ),
    ]
