# Generated by Django 3.2.9 on 2021-12-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_result_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='massage',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='time',
            field=models.TextField(default=None, null=True),
        ),
    ]
