# Generated by Django 3.2.9 on 2021-12-08 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_meeting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.TextField(default=datetime.date(2021, 12, 8)),
        ),
    ]
