# Generated by Django 3.2.9 on 2021-12-05 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211205_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='massage',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='result',
            name='time',
            field=models.TextField(default=None),
        ),
    ]
