# Generated by Django 3.2.9 on 2021-12-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_meeting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='massage',
            field=models.TextField(choices=[('1', 'Масаж спини'), ('2', 'Масаж шиї'), ('3', 'Мануальна терапія'), ('4', 'Антицилюлітний масаж')], default='1'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time',
            field=models.TextField(choices=[('1', '10:00'), ('2', '11:00'), ('3', '12:00'), ('4', '13:00'), ('5', '14:00'), ('6', '15:00'), ('7', '16:00'), ('8', '17:00'), ('9', '18:00')], default='6'),
        ),
    ]
