# Generated by Django 3.2.9 on 2021-12-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_result_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={},
        ),
        migrations.AddField(
            model_name='result',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
